# coding: utf-8

# flake8: noqa
"""
    Cities API

    My API for US postal code  # noqa: E501

    The version of the OpenAPI document: v1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from openapi_client.models.error import Error
from openapi_client.models.state import State
