# coding: utf-8

"""
    Cities API

    My API for US postal code  # noqa: E501

    The version of the OpenAPI document: v1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.error import Error  # noqa: E501
from openapi_client.rest import ApiException


class TestError(unittest.TestCase):
    """Error unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testError(self):
        """Test Error"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.error.Error()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
