# coding: utf-8

"""
    Cities API

    My API for US postal code  # noqa: E501

    The version of the OpenAPI document: v1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.state import State  # noqa: E501
from openapi_client.rest import ApiException


class TestState(unittest.TestCase):
    """State unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testState(self):
        """Test State"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.state.State()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
