# coding: utf-8

"""
    Cities API

    My API for US postal code  # noqa: E501

    The version of the OpenAPI document: v1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.default_api import DefaultApi  # noqa: E501
from openapi_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_cites_from_state(self):
        """Test case for get_cites_from_state

        """
        pass

    def test_get_states(self):
        """Test case for get_states

        """
        pass


if __name__ == '__main__':
    unittest.main()
